---
controller_host: "https://controller.{{ ocp_ingress_domain[0] }}"
controller_user: admin
controller_password: "{{ controller_password }}"
eda_host: "https://eda.{{ ocp_ingress_domain[0] }}"
eda_user: admin
eda_password: "{{ ansible_eda_instance_admin_password }}"

python_interpreter: "{% raw %}{{ ansible_playbook_python }}{% endraw %}"

organizations:
  - name: "JdA"
    description: "Organization for Junta de Andalucia POC"


teams: []

users: 
  - username: "selfservice"
    first_name: "Catalog"
    last_name: "Service"
    is_superuser: false
    password: "{{ user_pass }}"

admin_users: []

auditor_users: []

inventories: 
  - name: "Automation Controller Inventory"
    desc: "Automation Controller Inventory"
    org: Default
    vars: {}
  - name: "Networking Infrastructure"
    desc: "Networking Infrastructure"
    org: Default
    vars:
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
      ansible_python_interpreter: python

inventory_sources:
   - name: "Servicenow Inventory Source"
     desc: "Servicenow Inventory Source"
     org: Default
     source: scm
     source_path: "inventory.now.yml" 
     project: "Ansible Pipelines Project"
     credential: "ServiceNow Credential"
     inventory: "Networking Infrastructure"

hosts: []

execution_enviroment: []

applications: []

scm_custom_credential_types:
  - name: "ServiceNow"
    kind: cloud
    inputs: "{{ lookup('file', 'credential-types/snow-inputs.json') }}"
    injectors: "{{ lookup('file', 'credential-types/snow-injectors.json') }}"

scm_credentials:
  - name: "Red Hat Ansible Automation Platform Credential"
    desc: "Red Hat Ansible Automation Platform Credential"
    org: JdA
    type: "Red Hat Ansible Automation Platform"
    inputs:
      host: "{{ controller_host }}"
      username: "{{ controller_user }}"
      password: "{{ controller_password }}"

  - name: "OpenShift API Bearer Token"
    desc: "OpenShift API Bearer Token"
    org: JdA
    type: "OpenShift or Kubernetes API Bearer Token"
    inputs:
      host: "{{ openshift_api }}"
      bearer_token: "{{ openshift_token }}"

  - name: "ServiceNow Credential"
    desc: "ServiceNow Credential"
    org: JdA
    type: "ServiceNow"
    inputs:
      sn_host: "{{ snow_instance_host }}"
      sn_username: "{{ snow_eda_username }}"
      sn_password: "{{ snow_eda_password }}"

scm_projects:
  - name: "JdA Private Cloud"
    desc: ""
    org: JdA
    git_url: "http://gitea.{{ ocp_ingress_domain[0] }}/gitea/ansible-pipelines.git"
    git_branch: master
    git_cred: ""
    update_on_launch: false

scm_jobtemplates:
  - name: "[JT] Trigger Cloud Router Deploy Workflow"
    org: Default
    inv: "Automation Controller Inventory"
    project: "Ansible Pipelines Project"
    playbook: "playbooks/controller/trigger_deploy_workflow.yml"
    creds:
      - "Red Hat Ansible Automation Platform Credential"
      - "ServiceNow Credential"
    use_fact_cache: false
    ask_limit_on_launch: false
    ask_variables_on_launch: true
    allow_simultaneous: true
    execution_environment: "Ansible EDA Execution Environment"
    extra_vars:
      ansible_demo_namespace: "{{ ansible_demo_namespace }}"


scm_jobtemplates_survey: []

scm_workflowjobtemplates:
  - name: "[WF] Check Device operational State"
    org: Default
    inv: ""
    ask_variables_on_launch: true
    ask_limit_on_launch: true
    extra_vars: {"rulebooks": ["Kafka Rulebook"]}
    allow_simultaneous: true
    steps:
       - identifier: "Check Cloud Router BGP operational state"
         unified_job_template:
           organization:
             name: Default
           name: "[JT] Check Cloud Router BGP operational state"
           type: job_template
         credentials: []
         related:
           success_nodes: []
           failure_nodes: 
             - identifier: "Open Servicenow Incident"
           always_nodes: []
           credentials: []
       - identifier: Open Servicenow Incident
         unified_job_template:
           organization:
             name: Default
           name: "[JT] Open Servicenow Incident"
           type: job_template
         credentials: []
         related:
           success_nodes:
             - identifier: "Stop EDA Rulebook"
           failure_nodes: []
           always_nodes: []
           credentials: []
       - identifier: Stop EDA Rulebook
         unified_job_template:
           organization:
             name: Default
           name: "[JT] Stop EDA Rulebook"
           type: job_template
         credentials: []
         related:
           success_nodes:
             - identifier: "Fix Cloud Router BGP operational state"
           failure_nodes: []
           always_nodes: []
           credentials: []
       - identifier: Fix Cloud Router BGP operational state
         unified_job_template:
           organization:
             name: Default
           name: "[JT] Fix Cloud Router BGP operational state"
           type: job_template
         credentials: []
         related:
           success_nodes:
             - identifier: "Post-Check Cloud Router BGP operational state"
           failure_nodes: []
           always_nodes: []
           credentials: []
       - identifier: "Post-Check Cloud Router BGP operational state"
         unified_job_template:
           organization:
             name: Default
           name: "[JT] Check Cloud Router BGP operational state"
           type: job_template
         credentials: []
         related:
           success_nodes:
             - identifier: "Start EDA Rulebook"
           failure_nodes: []
           always_nodes: []
           credentials: []
       - identifier: Start EDA Rulebook
         unified_job_template:
           organization:
             name: Default
           name: "[JT] Start EDA Rulebook"
           type: job_template
         credentials: []
         related:
           success_nodes:
             - identifier: "Close Servicenow Incident"
           failure_nodes: []
           always_nodes: []
           credentials: []
       - identifier: Close Servicenow Incident
         unified_job_template:
           organization:
             name: Default
           name: "[JT] Close Servicenow Incident"
           type: job_template
         credentials: []


scm_workflowjobtemplates_webhook: []
scm_workflowjobtemplates_survey: []
