---

packages:
  - python-pip
  - python3-firewall
  - firewalld
  - vim
  - curl
  - cockpit
  - podman
  - chrony
  - net-tools

users:
  - login: "ops"
    group: "wheel"

fw_rules:
  - port: 9090
    protocol: "tcp"

services:
  - "cockpit.service"
  - "firewalld.service"