---

- name: Deploy Cloud VMs using Terraform
  hosts: localhost
  gather_facts: false
  vars:
    tf_plan_dir: "{{ playbook_dir }}/terraform"  # Adjust this path as needed
  vars_files:
    - vars/cloud.yml
  tasks:

    - name: Clone the repository with Terraform templates
      ansible.builtin.git:
        repo: 'git@github.com:lboubeta/terraform-example.git'
        dest: '{{ tf_plan_dir }}'
        version: 'main'
        force: true
      tags: clone

    - name: Define the backend configuration at init
      cloud.terraform.terraform:
        project_path: '{{ tf_plan_dir }}'
        state: "{{ infrastructure_state | default('present') }}"
        force_init: true
        backend_config:
          region: "eu-west-1"
          bucket: "wintest-tfstate-bucket"
          key: "terraform.tfstate"
      register: terraform_apply

    - name: Display Terraform apply output
      ansible.builtin.debug:
        var: terraform_apply.stdout_lines
      when: terraform_apply.changed

    - name: Display Terraform apply output
      ansible.builtin.debug:
        var: terraform_apply.stdout_errors
      when: terraform_apply.failed
