---

- name: Deploy Cloud VMs using Terraform
  hosts: localhost
  gather_facts: false
  vars:
    tf_plan_dir: "{{ playbook_dir }}/terraform"  # Adjust this path as needed
    backend_s3_bucket: "lboubeta-tfstate-bucket"
    backend_s3_key: "terraform.tfstate"
    backend_region: "eu-west-1"
  vars_files:
    - vars/cloud.yml
  tasks:

    - name: Clone the repository with Terraform templates
      ansible.builtin.git:
        repo: '{{ plan_repo_url }}'
        dest: '{{ tf_plan_dir }}'
        version: 'main'
        force: true
        accept_hostkey: true
      tags: clone

    - name: Apply Terraform configuration
      block:

        - name: Define the backend configuration at init
          cloud.terraform.terraform:
            project_path: '{{ tf_plan_dir }}'
            state: "{{ infrastructure_state | default('present') }}"
            force_init: true
            backend_config:
              region: "{{ backend_region }}"
              bucket: "{{ backend_s3_bucket }}"
              key: "{{ backend_s3_key }}"
          register: terraform_apply
          notify: Display Terraform apply output

      rescue:

        - name: Display Terraform apply errors
          ansible.builtin.debug:
            var: terraform_apply.stdout_errors

        - name: Propagate Terraform failure
          ansible.builtin.fail:
            msg: Terraform apply failed; see previous task output.

  handlers:

    - name: Display Terraform apply output
      ansible.builtin.debug:
        var: terraform_apply.stdout_lines
